package ar.edu.untref.aydoo;

/**
 * Created by hernan on 24/03/17.
 */
public enum Province {

    CABA, BUENOS_AIRES, JUJUY, SALTA, TUCUMAN, SANTIAGO_DEL_ESTERO, MISIONES, CORRIENTES, FORMOSA, CHACHO, CATAMARCA, CORDOBA, ENTRE_RIOS,
    LA_PAMPA, MENDOZA, SAN_LUIS, SAN_JUAN, LA_RIOJA, SANTA_FE, CHUBUT, SANTA_CRUZ, NEUQUEN, RIO_NEGRO, TIERRA_DEL_FUEGO

}
